---
info:
  description: Training configuration repo
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@service-registry-jlanger.cfapps.io/eureka
      
eureka.instance.hostname: ${vcap.application.uris[0]}
eureka.instance.nonSecurePort: 80
