---
spring:
  profiles: cloud

message: That's the updated company specific configuration for the cloud

---
spring:
  profiles: dev

message: That's the updated company specific configuration for development